### PR TITLE
fix(payments): separate redirect constructor from authorization hook

### PR DESCRIPTION
**Pull request by blaggacao**
Reincarnation of https://github.com/frappe/erpnext/pull/37502 for the same reasons

Sister PR: https://github.com/frappe/payments/pull/57

Please also merge #31

### CODE REVIEW

**Comment by s-aga-r** [comment]
@rohitwaghchaure

**Comment by blaggacao** [comment]
@rohitwaghchaure This blocks development on a PayZen implementation (or for that matter any [correct] implementation with an IPN &mdash; where we can't know if the flow is also return by the client in parallel).

**Comment by blaggacao** [comment]
@rohitwaghchaure could you please help with this PR?

**Comment by GeoCommander** [comment]
@rohitwaghchaure we need to merge this

**Comment by blaggacao** [comment]
Superseded by https://github.com/frappe/payments/pull/53 and https://github.com/frappe/frappe/pull/25952

**Pull request closed without merging**
